language: java
jdk:
- oraclejdk8
script:
- mvn test -Dtest=Login51abrownCom
sudo: required
dist: trusty
addons:
 chrome: stable
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
